version: '2.1'
services:
  receiver:
    build:
      context: .
      dockerfile: test-server.Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ 2>&1 | grep \"426 Upgrade Required\" -"]
      interval: 2s
      timeout: 1s
      retries: 5
  sender:
    build: .
    ports:
      - "80:80"
    environment:
      - FORWARD_LOGS_URL=ws://receiver:8080/
      - FORWARD_LOGS_DEBUG=true
    depends_on:
      receiver:
        condition: service_healthy