version: '2.1'
services:
  test-server:
    build:
      context: .
      dockerfile: test-server.Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ 2>&1 | grep \"426 Upgrade Required\" -"]
      interval: 2s
      timeout: 1s
      retries: 5
  nginx:
    build: .
    ports:
      - "80:80"
    environment:
      - FORWARD_LOGS_URL=ws://test-server:8080/
      - FORWARD_LOGS_DEBUG=true
    depends_on:
      test-server:
        condition: service_healthy